### ISSUE TITLE
allow firmwares to be uploaded without the magic marker

### ISSUE THREAD

**Issue by sumnerboy12** [jpmens/homie-ota#11]
- would need to allow the user to enter the firmware name and version manually

**Comment by jpmens** [comment]
Very low priority IMO.

**Comment by marvinroger** [comment]
I've made the new v2 `Homie_setFirmware()` mandatory (the sketch won't run if the function is not called), so this should not be a problem anymore.

**Comment by jpmens** [comment]
Very good, thank you.
