### ISSUE TITLE
display published node property values in device detail page

### ISSUE THREAD

**Issue by sumnerboy12** [jpmens/homie-ota#13]
e.g. sensor readings etc

**Comment by jpmens** [comment]
Like this? 

![jmbp-2739](https://cloud.githubusercontent.com/assets/60706/14979645/f119a204-1123-11e6-82ba-985c84b53d80.png)

**Comment by sumnerboy12** [comment]
Yes exactly like that...although perhaps in a separate table away from the _system_ pubs... ;)

**Comment by jpmens** [comment]
I knew that would come as soon as I hit _push_ ...

**Comment by sumnerboy12** [comment]
You have to admit it looks a bit sloppy with them in dispersed amongst 
the system topics...

Not that I am complaining of course.

**Comment by jpmens** [comment]
Of course. And yes. ;-)

**Comment by jpmens** [comment]
![jmbp-2740](https://cloud.githubusercontent.com/assets/60706/14980544/a4e147d8-1129-11e6-8725-92aad671634e.png)

**Comment by sumnerboy12** [comment]
Atta-boy!!
