### ISSUE TITLE
Remove devices from device inventory

### ISSUE THREAD

**Issue by jalmeroth** [jpmens/homie-ota#17]
Is there any way to remove devices from the device inventory or to re-build it?

**Comment by jpmens** [comment]
Not in the "UI", but you can manually remove `inventory.json` (and `sensors.json`) from within the `firmwares/` directory and then restart `homie-ota`.

**Comment by sumnerboy12** [comment]
Would also need to clear the various retained messages from your broker.

**Comment by jalmeroth** [comment]
Ok, thank you.
