### ISSUE TITLE
OTA on EST-01

### ISSUE THREAD

**Issue by mikecay** [jpmens/homie-ota#23]
Hi,
When I do the OTA to an ESP-01 the process starts but then fails/stops.  Is this because ESP-01 only has 1MB of memory?

Thank you,
Mike

**Comment by jpmens** [comment]
I believe that is the case, yes.

**Comment by jalmeroth** [comment]
Hi Mike,

I had a similar issue and could solve it:
https://github.com/jpmens/homie-ota/issues/12#issuecomment-223739732

Hope this helps,
Jan
