### ISSUE TITLE
Homie 2.0: wrong version published to $ota

### ISSUE THREAD

**Issue by ghost** [jpmens/homie-ota#31]
`homie-ota` publishes a string like `0123456789@1.0.0` to the `$ota` topic. Mosquitto log:

```
homie/my-device/$implementation/payload <firmware blob>
homie/my-device/$ota 0123456789@1.0.0
```

However, [Homie 2.0](https://github.com/marvinroger/homie/tree/v2) wants just the new firmware version number (`1.0.0`) to be published to the `device/$ota` topic.

As a result, `homie-esp8266` (2.0 branch) always updates firmware, even if the new firmware version number equals the currently running firmware version.

**Comment by jpmens** [comment]
closed via #32
