### ISSUE TITLE
ota failed

### ISSUE THREAD

**Issue by NegativeFeedback** [jpmens/homie-ota#45]
I am having problem getting devices to update. Using the latest homie-ota in both log and console not seeing any kind of issue and firmware parser gives output.

I have tried both homie 1.5 and 2. 1.5 goes through the process and starts a ota but gives a update failed. I do not know where I can get additional information on this as to why it failed.

in homie 2.0(master I dont see a actual release) it starts a update process but then gives a stack dump with something about error 3. Iknow there is probab;y somewhere else I can find more infomation to diagnose this I just dont know where.

Thanks

**Comment by Gulaschcowboy** [comment]
Homie 2.0 OTA issue may be related to https://github.com/marvinroger/homie-esp8266/issues/204 !?
Do you use Windows or Linux to compile? Arduino IDE or PlatformIO?

**Comment by NegativeFeedback** [comment]
Linux and both. both seemed to fail the same way, but unlike #204 There was never a success in the log.

**Comment by jpmens** [comment]
This should now work. Edited to add: by 'work' I mean it will no longer return 403 to http OTA in Homie 1.5. Whether or not MQTT-based OTAs work is another question: in terms of homie-ota it looks good, but there's still something not quite right in Homie2.0
