### ISSUE TITLE
OTA for Homie 1.5 broken in spite of supposed fix

### ISSUE THREAD

**Issue by alarmschaben** [jpmens/homie-ota#47]
First of all, thanks for the great tool!

It appears that e04712109fbd1f5a877e22fe1ab644dbda5ac03e intends to enable backwards compatibility for Home 1.5 devices using the old multiple '=' convention. 

However, when trying to update the firmware on a Home 1.5 device with the Homie version in platform.io (which I think is 1.5), the OTA request fails with

    File "./homie-ota.py", line 410, in ota
        device, f = headers.get('X-Esp8266-Version', None).split('=')
    ValueError: too many values to unpack

My weak python-foo tells me that homie-ota is actually expecting a 2.0-style header with the '->' convention.

**Comment by jpmens** [comment]
closed via #48
