### ISSUE TITLE
Provide non-rpi Dockerfile

### ISSUE THREAD

**Issue by hamishfagg** [jpmens/homie-ota#49]
Hi,
A normal alpine linux dockerhib repo would be great, to allow those of us without rpis to install directly without altering the dockerfile.

**Comment by hamishfagg** [comment]
Till this is done I have created this image: https://hub.docker.com/r/ivdata/homie-ota/
If you use ivdata/homie-ota:latest it will support both r-pi and amd64 based PCs.

**Comment by hamishfagg** [comment]
@jpmens In my PR I set up everything to point to valentinvieriu/homie on dockerhub but it seems like those images are not being maintained.

Are you interested in providing the images on dockerhub yourself? Otherwise I can do it, but I don't think there's a way to automate the build process since this is not my git repo.

**Comment by jpmens** [comment]
I'd appreciate if you do it; I can, if you mail me the appropriate token/URL, set up a trigger to kick your Docker build from this repository whenever a commit is made. Talk to me at jp()mens.de when you have time.

**Comment by hamishfagg** [comment]
The problem is I can't set your repo as a source for the build. Regardless, you can't build arm images on Dockerhub anyway =)
I will just set up some cron jobs to look at your repo here. I'll close this when it's working.

**Comment by jpmens** [comment]
I'll gladly set up any type of notification Github has to alert you, e.g a Webhook or (drumb roll) MQTT notification, which Github also has.
