### ISSUE TITLE
Homie v2 support

### ISSUE THREAD

**Issue by pwrsoft** [jpmens/homie-ota#52]
There are some changes to MQTT API.
Can you share your thoughts - how about supporting homie v2?

**Comment by ThomDietrich** [comment]
Came here to ask the same question. With Homie 2.0 getting more and more popular, support by homie-ota would be great.

**Comment by NemoN** [comment]
homie-ota is running flawless with homie 2.0 for me

**Comment by pwrsoft** [comment]
The format of MQTT messages changed from devices/12345678 to homie/1234567890ab
Changed MQTT_SENSOR_PREFIX  = homie in homie.config - the device statistics are now present on the home page.

The only thing that still doesn't work are OTA updates: I tried to apply OTA update and the device is now offline, so now I need to dig it out of the installation place, disassemble it and do a manual firmware upgrade...

There are changes to OTA updates procedure in v.2 compared to v1.5 of Homie (as far as I understood)  - so, can someone proof this?

**Comment by ThomDietrich** [comment]
I've used homie-ota with Homie 2.0 firmware devices without problems. The OTA routine seemed to work as expected (I had unrelated issues). If it's in fact compatible, that should be stated in the readme.
@pwrsoft I'm not sure about your issue. The base topic name is an option you can set as you wish.

**Comment by pwrsoft** [comment]
@ThomDietrich thank you for you reply!

PS: Closing this topic while opening a new, more specific – OTA updates issue.
