### ISSUE TITLE
Homie v2.0 OTA updates issue

### ISSUE THREAD

**Issue by pwrsoft** [jpmens/homie-ota#53]
Here comes the OTA notes for v1.5:
https://github.com/marvinroger/homie-esp8266/blob/v1.5.0/docs/4.-OTA.md

and the changes for OTA update in v2.0:
https://homie-esp8266.readme.io/v2.0.0/docs/ota-configuration-updates

OTA is now done over MQTT

Source: https://github.com/marvinroger/homie-esp8266/issues/87

Could you please implement OTA updates for v2.0 (which was the primary reason for using homie-ota)?

Thanks!

**Comment by egon0** [comment]
I'm ota-updating Homie v2 nodes with homie-ota without any problems.

**Comment by derp000herp** [comment]
Encountered a couple of issues which I'm guessing are as a result of homie v2:
- Device list doesn't get populated at all. Cant even attempt an ota update.
- When trying to upload a compiled sketch I get the following error:
`Cannot write ./firmwares/itead-sonoff-buton�Dk�uj?>�1.0.0�0H�switchj?>�1.0.5�0H����Texample-firmware-1.0.0�0H�switchj?>�1.0.5.bin: file() argument 1 must be encoded string without null bytes, not str`

Thank you for your time.

**Comment by jaharkes** [comment]
Homie v2 already adds the necessary magic strings for OTA naming in homie.setFirmware, see marvinroger/homie-esp8266@e73b3af066bf7daf3a551803affcb884ee2db066 in src/Homie.hpp. So it is possible that when you follow the example sketch here you end up adding the magic bytes twice which could explain the odd filenames observed by @derp00herp.
