### ISSUE TITLE
Homie OTA is not working

### ISSUE THREAD

**Issue by itsjustvenky** [jpmens/homie-ota#59]
I just upgraded to Homie ESP8266 to latest updates (07-July) and the Homie-OTA stopped working. I tried to debug the issue but couldn't find the exact issue. Before upgrading Homie-ESP8266 and Homie-OTA, the upgrading ESP8266 via Homie-OTA used to work. 

Has anybody has the problem.
Let me know thanks.

**Comment by TaneTsai** [comment]
I changed MQTT_SENSOR_PREFIX in homie-ota.ini from "devices" to "homie", then it works.
