### ISSUE TITLE
homie-ota not running in docker

### ISSUE THREAD

**Issue by keesma** [jpmens/homie-ota#64]
I am trying to run homie-ota in docker (RancherOS v1.1.0 (4.9.45).
After starting it I get the error message below.
I am fairly new to docker. Not sure if it is related to docker or e.g the commandline parameters.
On the internet i cannot find similar issues nor solutions.
Who can help me fix this?

`6-1-2018 10:32:08Traceback (most recent call last):
6-1-2018 10:32:08  File "homie-ota.py", line 40, in <module>
6-1-2018 10:32:08    DEBUG = config.getboolean("global", "DEBUG")
6-1-2018 10:32:08  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
6-1-2018 10:32:08    v = self.get(section, option)
6-1-2018 10:32:08  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
6-1-2018 10:32:08    raise NoSectionError(section)
6-1-2018 10:32:08ConfigParser.NoSectionError: No section: 'global'`

**Comment by kylegordon** [comment]
That sounds like a failure to read or parse the homie-ota.ini configuration file. 

The 'global' keyword should be encased in brackets, as demoed at https://github.com/jpmens/homie-ota/blob/master/homie-ota.ini.example

**Comment by keesma** [comment]
Thanks for the tip. It pointed me in the right direction.
homie-ota.ini is not part of the docker image. So I had to create it on the docker host and pass it to the home-ota docker. If you want to access the docker image outside the container then also map a port (option -p). It is running fine now with:

`docker run --name homie-ota -p 9080:9080 -v /home/rancher/homie-ota/homie-ota.ini:/app/homie-ota.ini ivdata/homie-ota`
