### ISSUE TITLE
Check if devices that match device topic are homie devices

### ISSUE THREAD

**Issue by mverleun** [jpmens/homie-ota#75]
I've got a mix of homie and non-homie based devices who all publish to the same topic.
All devices show up in the device overview of homie-ota, but the non-homie based devices are shown offline (of course) and can not be updated with different firmware (of course again.)

Is it possible to be more selective and only show devices that publish to one or more sub-topics that are specific to homie devices?

**Comment by jpmens** [comment]
I think we could enhance home-ota to provide that.

**Comment by mverleun** [comment]
That would be great and much appreciated.
