### ISSUE TITLE
PR #77 breaks Inventory display for Homie 2.0.1 devices

### ISSUE THREAD

**Issue by fvdpol** [jpmens/homie-ota#78]
PR #77  breaks compatibility with the Homie 2.0.1 devices (which is still the latest 'official' released version for ESP8266 devices).  

The inventory page does not show Online, Signal, IP, Uptime for Homie 2.0.1 devices anymore

with original templates/inventory.tpl:
![image](https://user-images.githubusercontent.com/1499454/51075869-ac66d480-1691-11e9-8d5d-87911501a2b1.png)

with the new/updated templates/inventory.tpl:
![image](https://user-images.githubusercontent.com/1499454/51075888-eb952580-1691-11e9-97e1-1172f0a7d262.png)

**Comment by jpmens** [comment]
Closed via #79
