### ISSUE TITLE
ota update with fw_name `wemos-dht22` ignored (but `wemos-dht` works)

### ISSUE THREAD

**Issue by sumnerboy12** [jpmens/homie-ota#8]
uploaded firmware with fw_name `wemos-dht22` and fw_version `0.0.1` - tried over a dozen times to two different Wemos devices. The OTA update request is just ignored. I.e. the pub is made by `homie-ota` to `/$ota` but the device never restarts in config mode.

changing fw_name to `wemos-dht` and the OTA update was picked up first time.

might be a Homie issue?

**Comment by jpmens** [comment]
The combination of name + `@` + version ist just too long: Homie says

```
const unsigned char MAX_FIRMWARE_VERSION_LENGTH = sizeof("v1.0.0-alpha+001");
...
if (strlen(payload) + 1 <= MAX_FIRMWARE_VERSION_LENGTH) {

```

Compare these two strings now:

```
v1.0.0-alpha+001
wemos-dht22@0.0.1
```

As Christoph reported yesterday, Homie then prints on the console:

```
OTA available (version xxxxxxxx@0.0.1)
Version string received is too long
```

**Comment by sumnerboy12** [comment]
right - so we should really build some validation into `homie-ota` to stop this?

**Comment by sumnerboy12** [comment]
snap - we could try to be smart and shrink the fw-name - afterall we have control over the filename and what we pub to `$ota`.

**Comment by jpmens** [comment]
Shrinking the name is going to cause confusion, and it's hard to get it right (i.e. keep a halfways sensible name and not overwrite something which exists).

We have 16 characters in total (name-version) which Homie willl accept. I'm thinking along the lines of hashing the name. Keep the fwname visible in the UI, but tell Homie on $ota that it's `abcd002` (i.e. the hash). This would probably work, but it's confusing for all ...

**Comment by sumnerboy12** [comment]
ok - so it is just the `$ota` message we would hash - yes that would work. store it in our metadata and use that when looking up the f/w on the OTA request. the `$ota` pub is not very visible so I don't see this being a big problem, and people are going to create long f/w names.

**Comment by jpmens** [comment]
Idea:
1. Accept firmware, extract name / version, store as `Fnnnn@version.bin`, keeping track of original name to show in UI
2. On OTA publish `Fnnnn@version` to `/$ota`
3. On OTA request from device, deliver `Fnnnn@version.bin`

The `nnnn` is simply a counter we keep track of and increment on upload of a new firmware.

This way we provide Homie with a guaranteed short name _and_ we give the UI a decent firmware name to display.

**Comment by sumnerboy12** [comment]
or that...

**Comment by sumnerboy12** [comment]
I think safer to store file with proper filename, and just dynamically generate the OTA hash.

**Comment by sumnerboy12** [comment]
something like;

```
hash = hashlib.sha1()
hash.update(fw_name)
return hash.hexdigest()[:10]
```

where the final length would be variable depending on the version string (i.e. `12.34.567`)

**Comment by jpmens** [comment]
It's worth trying, and we cross our fingers for few hash collisions ;-)

**Comment by sumnerboy12** [comment]
Please test!

**Comment by jpmens** [comment]
As mentioned, this is 👍
